apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nirmata-external-secret
  namespace: nirmata-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: eksa-secret-store #The secret store name we have just created.
    kind: ClusterSecretStore
  target:
    name: nirmata-secret # Secret name in k8s
  data:
  - secretKey: nirmata-license-key # which key it's going to be stored
    remoteRef:
      key: nirmata-license-key # Our secret-name goes here
      property: nirmata-license-key
