---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-operator
  namespace: nirmata-system
spec:
  chart:
    spec:
      chart: enterprise-kyverno-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nirmata
        namespace: flux-system
      version: "v0.2.37"
  interval: 1m0s
  releaseName: kyverno-operator
  targetNamespace: nirmata-system
  valuesFrom:
  - kind: Secret
    name: nirmata-secret
    valuesKey: nirmata-license-key
    targetPath: licenseKey
